Repository Iliveinbianries/BitsBytesWrites, pull requests merged in 2023-10, with the labels that each got.

#12 Added Web Development file.
  Web/WhatIsWebDevelopement.md
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#64 content for ML
  ML/DeepLearning.md
  ML/NLP.md
  ML/SupervisedLearning.md
  ML/UnsupervisedLearning.md
  ML/WhatIsMl.md
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#65 Added content for Web/WhatIsNodeJS.md
  Web/WhatIsNodeJS.md
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#74 Add content in ML folder
  ML/MLEthics.md
Labels: hacktoberfest, hacktoberfest-accepted

#72 Added content for files present in ML folder
  ML/MLinMarketing.md
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#77 Added What is mongoDB
  Web/WhatisMongoDB.md
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#81 Discrete Mathematics README created and content added
  General/DiscreteMathematics.md
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#78 Updated ComputerVision.md
  ML/ComputerVision.md
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#84 What is low level language
  General/WhatIsLowLevelProgramming.md
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#85 ProbabilityInCS
  General/ProbabilityInCSE.md
Labels: good first issue, hacktoberfest, hacktoberfest-accepted, one-step-ahead
